# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ second-edition ]
  pull_request:
    branches: [ second-edition ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm audit
    - run: npm run development 
    - run: npm install lodash
    
  deploy:
     needs: build
     runs-on: ubuntu-latest

     steps:
      - name: SSH and deploy node app
        uses: appleboy/ssh-action@master
        with:
         host: 52.152.147.241
         username: administration
         key: Pass@123456789
         port: 22
         script: |
            cd ~/node-github-demo
            git pull origin master
            npm install --production
            pm2 restart node-app
